./../print_all_func_name ~/blender_kernels/kernel_0.cl > kernel_0_all_func 
./../print_all_func_name ~/blender_kernels/kernel_1.cl > kernel_1_all_func
./../print_all_func_name ~/blender_kernels/kernel_2.cl > kernel_2_all_func
./../print_all_func_name ~/blender_kernels/kernel_3.cl > kernel_3_all_func
./../print_all_func_name ~/blender_kernels/kernel_4.cl > kernel_4_all_func
./../print_all_func_name ~/blender_kernels/kernel_5.cl > kernel_5_all_func
./../print_all_func_name ~/blender_kernels/kernel_6.cl > kernel_6_all_func
./../print_all_func_name ~/blender_kernels/kernel_7.cl > kernel_7_all_func
./../print_all_func_name ~/blender_kernels/kernel_8.cl > kernel_8_all_func
./../print_all_func_name ~/blender_kernels/kernel_9.cl > kernel_9_all_func
