/* Generated by Cython 0.24.1 */

#ifndef __PYX_HAVE__calculator
#define __PYX_HAVE__calculator


#ifndef __PYX_HAVE_API__calculator

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(int) add(char *, int, int);
__PYX_EXTERN_C DL_IMPORT(int) sub(char *, int, int);

#endif /* !__PYX_HAVE_API__calculator */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcalculator(void);
#else
PyMODINIT_FUNC PyInit_calculator(void);
#endif

#endif /* !__PYX_HAVE__calculator */
